name: Bun

on: push

jobs:
  small:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        bun-version:
          - "1.1.13"
          - "latest"
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Setup
        run: bun install

      - name: Test
        run: VITEST_MODE='Bun' bunx vitest tests/small/

  # TODO(tai-kun): なんか失敗する。要調査。
  # medium:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 30
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       bun-version:
  #         - "1.1.13"
  #         - "latest"
  #       surrealdb-version:
  #         - "alpha"
  #         # - "v2.0.0"
  #         # - "latest"
  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: oven-sh/setup-bun@v2
  #       with:
  #         bun-version: ${{ matrix.bun-version }}

  #     - name: Setup
  #       run: bun install

  #     - name: Test
  #       run: |
  #         bash scripts/pretest/medium.sh ${{ matrix.surrealdb-version }}
  #         VITEST_MODE='Bun' bunx vitest tests/medium/

  #     - name: Logs
  #       run: cat /tmp/logs
  #       if: always()
