name: Chrome

on: push

jobs:
  small:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        browser-version:
          - "113"
          - "latest"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: ${{ matrix.browser-version }}
          install-dependencies: true
        id: setup-chrome

      - name: Prepare
        run: bash scripts/pretest/small.sh test-env/chrome

      - name: Test
        working-directory: test-env/chrome
        run: bash scripts/test.sh
        env:
          BROWSER_EXECUTABLE_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}

  medium:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        browser-version:
          - "113"
          - "latest"
        surrealdb-version:
          - "v1.5.0"
          - "latest"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: ${{ matrix.browser-version }}
          install-dependencies: true
        id: setup-chrome

      - name: Prepare
        run: bash scripts/pretest/medium.sh test-env/chrome ${{ matrix.surrealdb-version }}

      - name: Test
        working-directory: test-env/chrome
        run: bash scripts/test.sh
        env:
          BROWSER_EXECUTABLE_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}

  action-timeline:
    needs:
      - small
      - medium
    permissions:
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: Kesin11/actions-timeline@v2
