name: Firefox

on: push

jobs:
  small:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        # https://hub.docker.com/r/selenium/standalone-firefox/tags
        browser-version:
          - "100.0"
          - "latest"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Prepare
        id: prepare
        run: |
          name="$(openssl rand -hex 12)"
          docker run --name "$name" --rm -d --network host --shm-size=2g selenium/standalone-firefox:${{ matrix.browser-version }}
          echo "selenium_container_name=$name" >>$GITHUB_OUTPUT
          bash scripts/pretest/small.sh test-env/firefox
          while ! curl --retry 5 -sSL http://localhost:4444/wd/hub/status | jq -e '.value.ready' | grep -q true; do sleep 1; done
          curl -sSL http://localhost:4444/wd/hub/status | jq -e '.value.nodes'

      - name: Test
        timeout-minutes: 2 # 1 minute + overhead
        working-directory: test-env/firefox
        run: |
          bash scripts/test.sh

      - name: Cleanup
        if: always()
        run: |
          docker stop ${{ steps.prepare.outputs.selenium_container_name }} || true

  medium:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        # https://hub.docker.com/r/selenium/standalone-firefox/tags
        browser-version:
          - "100.0"
          - "latest"
        surrealdb-version:
          - "v1.5.0"
          - "latest"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Prepare
        id: prepare
        run: |
          name="$(openssl rand -hex 12)"
          docker run --name "$name" --rm -d --network host --shm-size=2g selenium/standalone-firefox:${{ matrix.browser-version }}
          echo "selenium_container_name=$name" >>$GITHUB_OUTPUT
          bash scripts/pretest/medium.sh test-env/firefox ${{ matrix.surrealdb-version }}
          while ! curl --retry 5 -sSL http://localhost:4444/wd/hub/status | jq -e '.value.ready' | grep -q true; do sleep 1; done
          curl -sSL http://localhost:4444/wd/hub/status | jq -e '.value.nodes'

      - name: Test
        timeout-minutes: 5
        working-directory: test-env/firefox
        run: |
          bash scripts/test.sh

      - name: Cleanup
        if: always()
        run: |
          docker stop ${{ steps.prepare.outputs.selenium_container_name }} || true
