name: GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/gh-pages.yml"
      - "src/**"
      - "package-lock.json"
      - "package.json"
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Build
        run: |
          npm ci
          npm run docs

      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs

      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment

